---
title: "Bivariate Viz"
---

Use this file to generate a professional looking **bivariate** visualization.  The visualization will not perfect the first time but you are expected to improve it throughout the semester especially after covering advanced topics such as effective viz.


```{r}
#loading graphical representation

library(ggplot2)


```


```{r}
#loading data

elections <- read.csv("https://mac-stat.github.io/data/election_2020_county.csv")



```

```{r}

install.packages("ggridges")

```


```{r}

library(ggridges)

```

```{r}

install.packages("forcats")

library(forcats)

```
```{r}

library(tidyverse)

```



```{r}
#| fig-cap: "Density Ridge plots of the U.S.A. states' Republican support percentages with color added to show historical voting alignment. Author: Torrey Johnson. Date: 2/28/2025"
#| fig-alt: "Density Ridge plots of the U.S.A. states' Republican support percentages with color added to show historical voting alignment. The upper U.S.A. states are red, and the lower are blue. The historically red states have higher amounts of Republican support percentage. The ridges are all unimodal."

ggplot(elections, aes(x = repub_pct_20, y = fct_reorder(state_abbr, repub_pct_20), fill = historical)) + 
  geom_density_ridges(alpha = 0.5) + 
  labs(y = "state", x = "2020 Republican support (%)", title = "2020 USA Election Republican Support % Density by State", fill = "Historical State Electoral Political Alignment", subtitle = "Color indicates historical political alignment of states, 2020 Republican Support (%) = % of the 
       vote that was for Republicans. Source: https://mac-stat.github.io/data/election_2020_county.csv. Author: bcheggeseth Date: Jun 19, 2024") + 
  scale_fill_manual(values = c("blue", "purple", "red"))

```
Finished
