---
title: "Trivariate Viz"
---

Use this file to generate a professional looking **trivariate** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.


```{r}
#load needed packages
library(ggplot2)
library(tidyverse)


```


```{r}

# Import data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))  

```


```{r}
#| fig-cap: "A scatterplot of the temperatures of locations with the x axis representing the location's temperature at 9:00 a.m. and the y axis representing the location's temperature at 3:00 p.m..The colors red green and blue for the points represent Hobart, Uluru and Wollongong respectively."
#| fig-alt:"A scatterplot of the temperatures of locations with the x axis representing the location's temperature at 9:00 a.m. and the y axis representing the location's temperature at 3:00 p.m..The colors red green and blue for the points represent Hobart, Uluru and Wollongong respectively. There is a strong positive correlation to the points and it looks like Hobart has the lowest temperatures on average. Uluru has the most range and also has the highest temperatures"

ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point() +
  labs(title = "Temperatures at 3am v.s. 9am at Hobart, Uluru, and Wollongong. ", subtitle = "Source: https://mac-stat.github.io/data/election_2020_county.csv. 
   Author: bcheggeseth
   Date: Jun 19, 2024 ", color = "Location of temp. taken", x = "Temperature at 9:00 a.m. (Celcius)", y = "Temperature at 3:00 p.m. (Celcius)")
  


```



